import Link from 'next/link'
import './globals.css'
import Navbar from '@/components/navbar'

export const metadata = {
  title: 'Mina Webpage',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main>
        {children}
        </main>
        <footer>
          this is a footer
        </footer>
      </body>
    </html>
  )
}
